import { ArrowLeft, CheckCircle2, Download, Monitor, PackageCheck, Smartphone, TriangleAlert } from 'lucide-react';
import type { MotionPairProject } from '../project/projectSchema';

type Validation = { errors: string[]; warnings: string[] };
export function ExportCenterPage({ project, target, onTargetChange, desktopValidation, mobileValidation, busy, onBack, onExport }: { project: MotionPairProject; target: 'desktop-web' | 'mobile-video'; onTargetChange: (target: 'desktop-web' | 'mobile-video') => void; desktopValidation: Validation; mobileValidation: Validation & { estimatedMb: number }; busy: boolean; onBack: () => void; onExport: () => void }) {
  const validation = target === 'mobile-video' ? mobileValidation : desktopValidation;
  const codec = target === 'mobile-video' ? 'H.264 MP4 · WebM fallback' : 'WebGL 2 · Offline ZIP';
  const output = target === 'mobile-video' ? `${project.mobileRender.width} × ${project.mobileRender.height} · ${project.mobileRender.fps} FPS` : project.canvas.aspectRatio === '9:16' ? '1080 × 1920 interactive Web' : 'Interactive Web Wallpaper';
  const estimated = target === 'mobile-video' ? `≈ ${mobileValidation.estimatedMb.toFixed(1)} MB video + bundle` : 'Assets + runtime ZIP';
  return <main className="hub-page export-center"><header className="hub-topbar"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Editor</button><div className="hub-brand"><span><PackageCheck size={18} /></span><b>Export Center</b></div></header><section className="hub-content"><div className="hub-heading"><span>READY FOR DELIVERY</span><h1>Choose how this wallpaper will be installed.</h1><p>Target-specific validation runs before packaging, so customers receive the right file and instructions.</p></div><div className="export-center-grid"><section><div className="export-target-cards"><button className={target === 'desktop-web' ? 'export-target-card selected' : 'export-target-card'} onClick={() => onTargetChange('desktop-web')}><Monitor size={24} /><span><b>Windows Interactive</b><small>Wallpaper Engine Web package</small></span><CheckCircle2 size={18} /></button><button className={target === 'mobile-video' ? 'export-target-card selected' : 'export-target-card'} onClick={() => onTargetChange('mobile-video')}><Smartphone size={24} /><span><b>Android Portrait Video</b><small>MP4 with WebM fallback</small></span><CheckCircle2 size={18} /></button></div><div className="export-spec-card"><div><span>FORMAT</span><b>{codec}</b></div><div><span>OUTPUT</span><b>{output}</b></div><div><span>ESTIMATED SIZE</span><b>{estimated}</b></div></div><div className="export-files"><b>Package contents</b>{target === 'mobile-video' ? <ul><li>Video MP4 or WebM</li><li>Static fallback JPG</li><li>Manifest and SHA-256 checksums</li><li>Android install instructions</li></ul> : <ul><li>Offline runtime and project.json</li><li>Aligned assets and difference mask</li><li>Preview, thumbnail, manifest and SHA-256</li><li>Wallpaper Engine install instructions</li></ul>}</div></section><aside className="export-validation"><span>VALIDATION</span><h2>{validation.errors.length === 0 ? 'Ready to export' : 'Fix before export'}</h2>{validation.errors.length === 0 && <div className="export-check pass"><CheckCircle2 size={16} /> All required checks passed.</div>}{validation.errors.map((error) => <div className="export-check" key={error}><TriangleAlert size={16} /> {error}</div>)}{validation.warnings.map((warning) => <div className="export-warning" key={warning}><TriangleAlert size={15} /> {warning}</div>)}<button className="primary-button export-run" disabled={busy || validation.errors.length > 0} onClick={onExport}><Download size={16} /> {busy ? 'Preparing export…' : target === 'mobile-video' ? 'Export mobile bundle' : 'Export desktop ZIP'}</button><small>Exports are local. No asset is uploaded.</small></aside></div></section></main>;
}
