import type { WallpaperPreset } from './types';

const pairInputs: WallpaperPreset['inputs'] = [
  { id: 'imageA', label: 'Base image A', required: true, accepts: ['image'], description: 'The visual state shown first.' },
  { id: 'imageB', label: 'Variant image B', required: true, accepts: ['image'], description: 'A closely aligned variation of the base image.' },
];

export const portalRevealPreset: WallpaperPreset = { id: 'portal-reveal', version: 1, ordinal: '02', name: 'Portal Reveal', summary: 'A moving portal uncovers approved changed details from the variant.', category: 'interactive', status: 'ready', supportedTargets: ['desktop-web', 'mobile-video', 'both'], inputs: pairInputs, workflow: ['assets', 'canvas', 'align', 'difference', 'motion', 'effects', 'validate', 'export'], capabilities: { alignment: true, differenceMask: true, timeline: true, desktopPointer: true }, defaultSettings: { portal: { radius: 22, glow: 38, softness: 12 }, mobileMotion: { path: 'orbit', duration: 8, loop: 'repeat' } } };
export const beforeAfterSweepPreset: WallpaperPreset = { id: 'before-after-sweep', version: 1, ordinal: '03', name: 'Before / After Sweep', summary: 'A controlled divider travels across the pair for an editorial comparison.', category: 'timeline', status: 'beta', supportedTargets: ['desktop-web', 'mobile-video', 'both'], inputs: pairInputs, workflow: ['assets', 'canvas', 'align', 'motion', 'effects', 'validate', 'export'], capabilities: { alignment: true, differenceMask: false, timeline: true, desktopPointer: false }, defaultSettings: { sweep: { direction: 'horizontal', softness: 3, duration: 8 }, mobileMotion: { path: 'guided', duration: 8, loop: 'pingpong' } } };
export const transformationLoopPreset: WallpaperPreset = { id: 'transformation-loop', version: 1, ordinal: '04', name: 'Transformation Loop', summary: 'A seamless A-to-B-and-back transition designed for portrait video delivery.', category: 'timeline', status: 'beta', supportedTargets: ['mobile-video'], inputs: pairInputs, workflow: ['assets', 'canvas', 'align', 'motion', 'effects', 'validate', 'export'], capabilities: { alignment: true, differenceMask: false, timeline: true, desktopPointer: false }, defaultSettings: { transform: { duration: 8, curve: 'cosine' }, mobileMotion: { path: 'breathe', duration: 8, loop: 'pingpong' } } };
