import { useEffect, useRef, useState } from 'react';
import type { ProjectAsset } from './project/projectSchema';

export function DepthMapEditor({ asset, onChange }: { asset: ProjectAsset; onChange: (asset: ProjectAsset) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const imageRef = useRef<HTMLImageElement | null>(null); const drawing = useRef(false); const [brush, setBrush] = useState(12); const [mode, setMode] = useState<'raise' | 'lower'>('raise');
  useEffect(() => { const image = new Image(); image.onload = () => { imageRef.current = image; const canvas = canvasRef.current; if (!canvas) return; canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; canvas.getContext('2d')?.drawImage(image, 0, 0); }; image.src = asset.source; return () => { image.onload = null; }; }, [asset.source]);
  const paint = (event: React.PointerEvent<HTMLCanvasElement>) => { const canvas = canvasRef.current; const context = canvas?.getContext('2d'); if (!canvas || !context || !drawing.current) return; const rect = canvas.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width * canvas.width; const y = (event.clientY - rect.top) / rect.height * canvas.height; context.globalCompositeOperation = 'source-over'; context.fillStyle = mode === 'raise' ? 'rgba(255,255,255,.22)' : 'rgba(0,0,0,.22)'; context.beginPath(); context.arc(x, y, brush / 100 * Math.min(canvas.width, canvas.height), 0, Math.PI * 2); context.fill(); };
  const commit = () => { const canvas = canvasRef.current; if (!canvas) return; canvas.toBlob((blob) => { if (!blob) return; const source = URL.createObjectURL(blob); onChange({ ...asset, source, mimeType: 'image/png', width: canvas.width, height: canvas.height, size: blob.size }); }, 'image/png'); };
  return <div className="depth-editor"><canvas ref={canvasRef} className="depth-editor-canvas" onPointerDown={(event) => { drawing.current = true; event.currentTarget.setPointerCapture(event.pointerId); paint(event); }} onPointerMove={paint} onPointerUp={() => { drawing.current = false; commit(); }} onPointerCancel={() => { drawing.current = false; }} aria-label="Depth map brush editor" /><div className="depth-editor-tools"><label>Brush <input type="range" min="2" max="40" value={brush} onChange={(event) => setBrush(Number(event.target.value))} /></label><button className={mode === 'raise' ? 'active' : ''} onClick={() => setMode('raise')}>Raise</button><button className={mode === 'lower' ? 'active' : ''} onClick={() => setMode('lower')}>Lower</button></div></div>;
}
